<?php
	$menu = $this->getMenu();
?>

<div class="menubuilder-configure-edit-container">

	<div class="content-header">
		<table cellspacing="0">
			<tbody><tr>
				<td style="width:50%;"><h3 class="head">Edit Menu &quot;<?php echo $menu->getLabel(); ?>&quot;</h3></td>
				<td class="a-right">
					<?php echo $this->getBackButtonHtml(); ?>
					<?php if( $menu->getId() ){ ?>
						<?php echo $this->getDeleteButtonHtml(); ?>
					<?php } ?>
					<?php echo $this->getSaveButtonHtml(); ?>
				</td>
			</tr>
		</tbody></table>
	</div>

	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend">Menu Settings</h4>
		</div>
		<div class="fieldset " id="settings">
			<div class="hor-scroll">
				<form name="mainMenuForm" id="mainMenuForm" action="" method="post">
					<input type="hidden" name="form_key" value="<?php echo Mage::getSingleton('core/session')->getFormKey(); ?>" />
					<input type="hidden" id="menu_id" name="menu_id" value="<?php echo $menu->getId(); ?>" />
					<input type="hidden" id="hiddenMenu" name="hiddenMenu" value="" />
					<table cellspacing="0" class="form-list">
						<tbody>
							<tr>
								<td class="label"><label for="menuLabel">Label</label></td>
								<td class="value">
									<input type="text" name="menuLabel" id="menuLabel" value="<?php echo $menu->getLabel(); ?>" />
									<br /><span class="comment">(only used internally)</span>
								</td>
							</tr>
						</tbody>
					</table>
				</form>
			</div>
		</div>
	</div>

	<div class="entry-edit">
		<div class="entry-edit-head">
			<h4 class="icon-head head-edit-form fieldset-legend">Menu Items</h4>
		</div>
		<div class="fieldset " id="settings">
			<div class="hor-scroll">
				<?php echo $this->getChildHtml( 'menubuilderpro.menu.tree' ); ?>
				<?php echo $this->getChildHtml( 'menubuilderpro.menu.options' ); ?>
			</div>
		</div>
	</div>

</div>